<a href="https://colab.research.google.com/github/arnabangel/arnabangel/blob/main-branch/Practice_Notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
fruits = ['apple', 'banana', 'cherry']
print(fruits)

fruits.insert(1, "orange")

print(fruits)

['apple', 'banana', 'cherry']
['apple', 'orange', 'banana', 'cherry']


In [ ]:
t = ("disco", 12, 4.5)
t[0][2]

's'

In [ ]:
# task 1
marks_scored = [99, 56, 40, 23, 67, 12, 88]
total_marks = 0
for marks in marks_scored:
  total_marks += marks
  if marks >= 40:
    print("Passed")
  else:
    print("Failed")

# task 2.1
i = 0
total_marks=total_marks+marks_scored[i]
print ("Total Marks scored:",total_marks)

# task 2.2
percentage = sum(marks_scored) / len(marks_scored)
print("Candidate has scored", percentage ,"percent")

# task 3
if percentage >=75 :
  print("A Grade")
elif percentage >=65 :
  print("B Grade")
elif percentage >=50 :
  print("C Grade")
elif percentage >=40 :
  print("D Grade")
else:
   print("Candidate Failed")

Passed
Passed
Passed
Failed
Passed
Failed
Passed
Total Marks scored: 484
Candidate has scored 55.0 percent
C Grade


In [ ]:
def factorial(n):
    if n == 0:
        return 1
    else:
        return n * factorial(n - 1)

In [ ]:
def addn(x,y):
    x= input ()
    y= input()
    z=x+y
    print (z)

In [ ]:
l=[4,3,5,7]
print(l)
l.sort(reverse=True)
print (l)

[4, 3, 5, 7]
[7, 5, 4, 3]


In [ ]:
def factorial(n):
    if n == 0:
        return 1
    else:
        return n * factorial(n - 1)

In [ ]:
n = input ()
def factorial(n):
    if n == 0:
        return 1
    else:
        return n * factorial(n - 1)

7


In [ ]:
a= input ()
def facto(a):
  f=1
  for i in range ( 1, a+1):
    f=f*i
    return f

6


In [ ]:
a= input ()
print (a)
print (type(a))

5
5
<class 'str'>


In [ ]:
num = int (input ("enter a number:"))
factorial = 1
if num < 0:
  print ("factorial of negative does not exist")
  elif num == 0:
    print ("factorial of 0 is 1")
  else:
    for i in range (1,num+1):
      factorial = factorial*i
      print ("factorial of",num,"is",factorial)

SyntaxError: invalid syntax (<ipython-input-52-b6dcb881fc62>, line 5)

In [ ]:
# Python 3 program to find
# factorial of given number
def factorial(n):

    # single line to find factorial
    return 1 if (n==1 or n==0) else n * factorial(n - 1)

# Driver Code
num = int (input ("enter a number:"))
print("Factorial of",num,"is",factorial(num))


enter a number:4
Factorial of 4 is 24


In [ ]:
l=("Pythons syntax is easy to learn")
l1=("Pythons syntax is very clear")
new_l=l+(" & ")+l1
print (new_l)

Pythons syntax is easy to learn & Pythons syntax is very clear


In [ ]:
l=('Kumar_Ravi_003')
l1=l[6:10]
l2=l[0:5]
l3=l[11:14]
print (l1)
print (l2)
print (l3)
print (l)


Ravi
Kumar
003
Kumar_Ravi_003


In [ ]:
tup1 = ('Monty Python', 'British', 1969)
tup2= ('Python',)
tup3= tup1 + tup2
tup3



('Monty Python', 'British', 1969, 'Python')

In [ ]:
A = {5, 1, 3, 4, 4, 5, 6, 7}
B = {3, 3, 5, 5, 1 ,7 ,2}
print (A & B)
print (A|B)
print (A - B)
print (A ^ B)
(A.union(B)).difference(A.intersection(B))

{1, 3, 5, 7}
{1, 2, 3, 4, 5, 6, 7}
{4, 6}
{2, 4, 6}


{2, 4, 6}

In [ ]:
d = { 101:['Shiva', 24, 'Content Strategist'] ,102:['Udit',25,'Content Strategist'], 103:['Sonam', 28,'Sr Manager'], 104:['Ansari',29,'Product Lead' ],105:['Huzefa',32,'Project Manager' ]}
d
d [104]
print (d.get(104))

['Ansari', 29, 'Product Lead']


In [ ]:
d

{101: ['Shiva', 24, 'Content Strategist'],
 102: ['Udit', 25, 'Content Strategist'],
 103: ['Sonam', 28, 'Sr Manager'],
 104: ['Ansari', 29, 'Product Lead'],
 105: ['Huzefa', 32, 'Project Manager']}

In [ ]:
d={'Name': 'Monty', 'Profession': 'Singer' }
value = d.get('Label','NA')
print ("Label: ",value)

Label:  NA


In [ ]:
d={'Name': 'Monty', 'Profession': 'Singer','Label':'NA' }
value = d.get('Label','NA')
print ("Label= ",value)

Label=  NA


In [ ]:
from _typeshed import SupportsRead
d={'Jack Dorsey' : 'Twitter' , 'Tim Cook' : 'Apple','Jeff Bezos' : 'Amazon' ,'Mukesh Ambani' : 'RJIO'}
d.values()

ModuleNotFoundError: No module named '_typeshed'

In [ ]:
d={'Jack Dorsey' : 'Twitter' , 'Tim Cook' : 'Apple','Jeff Bezos' : 'Amazon' ,'Mukesh Ambani' : 'RJIO'}
sorted (d.values())

['Amazon', 'Apple', 'RJIO', 'Twitter']

In [ ]:
x= int (input())
if (x<10):
    print('No')
else:
    if (x>10 ):
        print('No')
    else:
        print('Yes')

10
Yes


In [ ]:
world_cups = {2023: ['India','Australia'], 2019 : ['England', 'New Zealand'], 2015:["Australia", "New Zealand"], 2011 : ["India", "Sri Lanka"], 2007: ["Australia", "Sri Lanka"], 2003: ["Australia", "India"]}

year = int(input("Enter year to check India made it to Finals in 20th century : "))

if year in world_cups :
    if "India" in world_cups[year] :
        print("India made it to Finals")
    else:
        print("India could not make it to Finals")

else:
    print("World cup wasnt played in", year)

Enter year to check India made it to Finals in 20th century : 2023
India made it to Finals


In [ ]:
world_cups = {2023: ['India','Australia'], 2019 : ['England', 'New Zealand'], 2015:["Australia", "New Zealand"], 2011 : ["India", "Sri Lanka"], 2007: ["Australia", "Sri Lanka"], 2003: ["Australia", "India"]}
world_cups [2023]

['India', 'Australia']

In [ ]:
input_str = str (input("Enter the String"))
value = input_str [0]
vowel = ("a e i o u")
if value in vowel:
  print ("word starts with a vowel")
else:
  print ("word does not start with vowel")


Enter the Stringanaconda
word starts with a vowel


In [ ]:
pin = input("Enter your four digit pin: ")
while pin != '1234':                           #Pre-set pin is 1234
    pin = input('Invalid input, please try again: ')
print("Pin validation successful.")

Enter your four digit pin: 1234
Pin validation successful.


In [ ]:
import sys    #required for exiting the code and displaying an error

pin = input("Enter your four digit pin: ")
attempt_count = 1
while pin != '1234':
    if attempt_count >= 3:
     sys.exit("Too many invalid attempts")   #error code
    pin = input('Invalid input, please try again: ')
    attempt_count += 1
print("Pin validation successful.")

Enter your four digit pin: 1234
Pin validation successful.


In [ ]:
L1 = [10, 20, 30, 24, 18]
L2 = [8, 14, 15, 20, 10]
L3 = [0, 1, 2, 3, 4]

for i in L3:
    L3[i] = L1[i] - L2[i]

In [ ]:
singers = ['VARMA', 'raj', 'Gupta', 'SaNdeeP']
singers = [singer.capitalize() for singer in singers]
print(singers)

['Varma', 'Raj', 'Gupta', 'Sandeep']


In [ ]:
d = {0: 'Fish', 1: 'Bird', 2: 'Mammal'}
for i in d:
    print(i)


SyntaxError: invalid syntax (<ipython-input-18-7382d27e9a91>, line 4)

In [ ]:
x=[1,2,3,4,5,6]
x[1::2]

[2, 4, 6]

In [ ]:
x= int (input(" enter the age "))
if (x<18):
    print('Cannot Vote')
else:
    if (x>=18 ):
        print('Congrats you can vote')

 enter the age 18
Congrats you can vote


In [ ]:
x= int (input(" enter the marks "))
if (x<60):
    print('Please study')
elif x >=60:
  print ("Can do better")
elif x>=70:
    print ("Good")
elif x>=80:
  print ("very good")
elif x>=90:
  print ("excellent")



 enter the marks 0
Please study


In [ ]:
x = [2,3,1,0,20]
print('The original list : ' + str(x))
res = [ele for ele in range(max(x)+1) if ele not in x]
print('The list of missing elements : ' + str (res))

The original list : [2, 3, 1, 0, 20]
The list of missing elements : [4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]


In [ ]:
x = [2,3,1,0,20]
for i in range (max(x)):
  if i not in x:
    print (i)

4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [ ]:
x = [4,5,6,7,8,9,19]
e=[]
for i in range (max(x)):
  if i not in x:
    e.append(i)
    print (i)

0
1
2
3
10
11
12
13
14
15
16
17
18


In [ ]:
x = [1,2,3]
s=0
for i in x:
  s=s+i
print ("Total Marks scored:",s)


Total Marks scored: 6


In [ ]:
num = input("Enter Number: ")
sum = 0

for i in num:
    sum = sum + int(i)

print(sum)



Enter Number: 12345
15


In [ ]:
x = 'UpgrAd EducatiOn'
z = ['a','e','i','o','u']
s = set()
for y in x.lower():
  if(y in z):
    s.add(y)
    print(len(s))


1
2
3
3
3
4
5


In [ ]:
x = "akAsh"
vowel = ['a','e','i','o','u']
for i in range(len(x)):
    if x[i] not in vowel:
        result = result + string[i]
        print("string without vowel", result)


NameError: name 'result' is not defined

In [ ]:
x="akAsh"
v = "aeiou"
y = ""
for i in x:
  if i.lower() not in v:
    y = y + i
  print(y)


k
k
ks
ksh


In [ ]:
def factorial_func(num):
  factorial = 1
  while ( num > 0 ) :
    if ( num == 1) :
      return factorial
      else:
        factorial = factorial * num
        num = num - 1

SyntaxError: invalid syntax (<ipython-input-55-c90499d43188>, line 6)

In [ ]:
def f(n):
  fact=1
  while n>0:
    fact=fact*n
    n=n-1
    return fact x= f(5)
    print(x)

SyntaxError: invalid syntax (<ipython-input-59-a503539ed1ff>, line 6)

In [ ]:
n = int(input("enter number"))
def f(n):
    fact=1
    while n>0:
        fact=fact*n
        n=n-1
    return fact
x= f(n)
print(x)

enter number5
120


In [ ]:
def reverse_words(sentence):
    words = sentence.split()
    reversed_words = list(map(lambda x: x[::-1], words))
    return ' '.join(reversed_words)
sentence = "s'teL ekat edoCteeL tsetnoc"
print(reverse_words(sentence))



Let's take LeetCode contest


In [ ]:
x = "s'teL ekat edoCteeL tsetnoc"
y = x[::-1].split()[::-1]
" ".join(y)


"Let's take LeetCode contest"

In [ ]:
s = input(str("enter string "))
def isPalindrome(s):
    return s == s[::-1]
ans = isPalindrome(s)
if ans:
    print("Yes")
else:
    print("No")

enter string babai
No


In [ ]:
x = [1,2,3,100,100,99,98,97]
x.sort()
print("Second largest element is:", x[-2])

Second largest element is: 100


In [ ]:
x = [1,2,3,100,100,100,100,99,98,97]
x.sort(reverse=True)
max=x[0]
max2 = 0
for i in x:
    if i < max:
        max2 = i
        break
        print(max2)

In [ ]:
print(max2)

99


In [ ]:
def facto(n):
    f = 1
    for i in range(n+1):
        f = f*i
    return f
f(6)

720

In [ ]:
x = "akAsh"
v = "aeiou"
y = ""
for i in x:
    if i.lower() not in v:
        y = y + i
print(y)

ksh


In [ ]:
x = 'UpgrAd EducatiOn'
z = ['a','e','i','o','u']
s = set() #only contains unique

for y in x.lower():
    if y in z:
        s.add(y)

In [ ]:
s

{'a', 'e', 'i', 'o', 'u'}

In [ ]:
ordinary_dict ={}

for i in range(2,21):
    if i % 2 == 0:
        ordinary_dict[i] = i**2

print(ordinary_dict)

{2: 4, 4: 16, 6: 36, 8: 64, 10: 100, 12: 144, 14: 196, 16: 256, 18: 324, 20: 400}


In [ ]:
updated_dict = {i : i**2 for i in range(2,21) if i % 2 ==0}
print(updated_dict)

{2: 4, 4: 16, 6: 36, 8: 64, 10: 100, 12: 144, 14: 196, 16: 256, 18: 324, 20: 400}


In [ ]:
word = input("Enter a word : ")
vowels = {i for i in word if i in "aeiou"}
vowels

Enter a word : arnab


{'a'}

In [ ]:
n = int(input())
squares_list = [n**2 for n in range(1,n+1)]
print(squares_list)

4
[1, 4, 9, 16]


In [ ]:
input_list = ['wood', 'old', 'apple', 'big', 'item', 'euphoria']
vowels = {'a', 'e', 'i', 'o', 'u'}
output_list = [word for word in input_list if word and word[0].lower() in vowels]
output_list




['old', 'apple', 'item', 'euphoria']

In [ ]:
d = {x.upper(): x*3 for x in 'acbd'}
print(d)

{'A': 'aaa', 'C': 'ccc', 'B': 'bbb', 'D': 'ddd'}


In [ ]:
def factorial(n):
  fact =1
  for i in range (i,n+1):
    fact*=i

  return fact

factorial(5)

UnboundLocalError: local variable 'i' referenced before assignment

In [ ]:
x = int(input("number x"))
y = int(input("number y"))
squares_list = [x**y]
print(squares_list)

number x6
number y7
[279936]


In [ ]:
d = { 101:['Shiva', 24, 'Content Strategist'] ,102:['Udit',25,'Content Strategist'], 103:['Sonam', 28,'Sr Manager'], 104:['Ansari',29,'Product Lead' ],105:['Huzefa',32,'Project Manager' ]}
print(d[101][2])

Content Strategist


In [ ]:
def list_diff(list1,list2):
    list3 = []
    for  i in range(0, len(list1)):
        list3.append(list1[i] - list2[i])
    return list3

L1 = [10, 20, 30, 24, 18]
L2 = [8, 14, 15, 20, 10]
print(list_diff(L1, L2))

[2, 6, 15, 4, 8]


In [ ]:
L1 = [2, 7, 8, 10, 3]

def func(y):
    return ____- 2 * y - 2

ans_list = [func(x) for  ______ ]
ans_list

35

In [ ]:
x=int(input("x="))
y=int(input("y="))
f=lambda x: x if x>y else y
f

x=9
y=3


<function __main__.<lambda>(x)>

In [ ]:
min = (lambda x, y: x if x < y else y)
min(101*99, 102*98)

9996

In [ ]:
students_data = {1:['Sam', 15] , 2:['Rob',18], 3:['Kyle', 16], 4:['Cornor',19], 5:['Trump',20]}

len(list(filter(lambda x : x[1] > 18, students_data.values())))

2

In [ ]:
from functools import reduce
list_1 = ['Paul','Ted']
reduce(lambda x,y: x + y,list_1)

'PaulTed'

In [ ]:
input_list = ['Santa Cruz','Santa fe','Mumbai','Delhi']
desireList = list(map(lambda x: x if x[0] == 'S' else '', input_list))
desireList.remove('')
print(len(desireList))

3


In [ ]:
input_list = [['Ankur', 'Avik', 'Kiran', 'Nitin'], ['Narang', 'Sarkar', 'R', 'Sareen']]
first_name = input_list[0]
last_name = input_list[1]
name = list(map(lambda x,y: x + " " + y, first_name, last_name))

print(name)

['Ankur Narang', 'Avik Sarkar', 'Kiran R', 'Nitin Sareen']


In [ ]:
input_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]
print("The original list is : " + str(input_list))
div_list = [5]
res = list(filter(lambda ele: all(ele % j == 0 for j in div_list), input_list))
print("All elements multiple of divisor list : " + str(res))

The original list is : [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]
All elements multiple of divisor list : [5, 10, 15, 20, 25, 30, 35, 40, 45, 50]


In [ ]:
input_list = ['soap', 'sharp', 'shy', 'silent', 'ship', 'summer', 'sheep']

sp = list(filter(lambda x: x[0] == 's' and x[-1]=='p', input_list))

print(sp)

['soap', 'sharp', 'ship', 'sheep']


In [ ]:
from functools import reduce
input_list =  ['All','you','have','to','fear','is','fear','itself']
list(reduce(lambda x,y: x+" "+y, input_list))

['A',
 'l',
 'l',
 ' ',
 'y',
 'o',
 'u',
 ' ',
 'h',
 'a',
 'v',
 'e',
 ' ',
 't',
 'o',
 ' ',
 'f',
 'e',
 'a',
 'r',
 ' ',
 'i',
 's',
 ' ',
 'f',
 'e',
 'a',
 'r',
 ' ',
 'i',
 't',
 's',
 'e',
 'l',
 'f']

In [ ]:
from functools import reduce
lst = [65,76,87,23,12,90,99]
largest_elem = reduce(max, lst)
print(largest_elem)

99


In [ ]:
# From a given array, extract all the elements which are greater than 'm' and less than 'n'.

import ast

input_list=ast.literal_eval(input())

m=int(input())

n=int(input())

import numpy as np

array_1 = np.array(input_list)

final_array  = array_1[(array_1 > m) & (array_1 < n)]

print(final_array)

10
9
7
[]


In [ ]:
import numpy as np
np.arange (3,35,2)

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33])

In [ ]:
import numpy as np
array_multipleof5 = np.arange(5,51,5)
print(array_multipleof5)

[ 5 10 15 20 25 30 35 40 45 50]


In [ ]:
n = int(input())

import numpy as np

x = np.ones((n,n), dtype=int)
x[1:-1,1:-1] = 0
print(x)

6
[[1 1 1 1 1 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 1 1 1 1 1]]


In [ ]:
import numpy as np

a = np. array([1,5,9])
b = np. array([3,0,2])
c= a + b
print (c)
np.arange(100)
np.arange(132).reshape(11,12)
np.array(range(1, 11*12+1))
np.unravel_index(99, (11,12))




[ 4  5 11]


(8, 3)

In [ ]:
import ast,sys
input_str = sys.stdin.read()
input_list = ast.literal_eval(input_str)
list_1 = input_list[0]
list_2 = input_list[1]
list_3 = input_list[2]

# Import NumPy
import numpy as np

# Write your code here
list_4 = np.transpose(list_3)
array_1 = np.vstack((list_1, list_2))
final_array = np.hstack((array_1, list_4))
print(final_array)

In [ ]:
import numpy as np
import pandas as pd
cars_df = pd.read_csv("cars.csv", header= None, index_col=0)

# set the column names
cars_df.columns = ['region', 'country', 'cars_per_cap', 'drive_right']
cars_df

FileNotFoundError: [Errno 2] No such file or directory: 'cars.csv'

In [ ]:
import numpy as np
import pandas as pd

# Read the CSV file from the URL
df = pd.read_csv('https://media-doselect.s3.amazonaws.com/generic/A08MajL8qN4rq72EpVJbAP1Rw/marks_1.csv', sep='|', header=None)

# Set the column names
df.columns = ['S.No.', 'Name', 'Subject', 'Maximum Marks', 'Marks Obtained', 'Percentage']
# Print the DataFrame
print(df)

In [ ]:
pip install pandas

In [ ]:
  df ["score"]
  type (df["score"])

NameError: name 'df' is not defined

In [ ]:
import pandas as pd
import numpy  as np

data = {"name":["Bill","Tom","Tim","John","Alex","Vanessa","Kate"],
       "score":[90,80,85,75,95,60,65],
       "sport":["Wrestling","Football","Skiing","Swimming","Tennis",
               "Karete","Surfing"],
       "sex":["M","M","M","M","F","F","F"]}

In [ ]:
data

{'name': ['Bill', 'Tom', 'Tim', 'John', 'Alex', 'Vanessa', 'Kate'],
 'score': [90, 80, 85, 75, 95, 60, 65],
 'sport': ['Wrestling',
  'Football',
  'Skiing',
  'Swimming',
  'Tennis',
  'Karete',
  'Surfing'],
 'sex': ['M', 'M', 'M', 'M', 'F', 'F', 'F']}

In [ ]:
type (data)

dict

In [ ]:
df=pd.DataFrame(data)
df

name  score      sport sex
0     Bill     90  Wrestling   M
1      Tom     80   Football   M
2      Tim     85     Skiing   M
3     John     75   Swimming   M
4     Alex     95     Tennis   F
5  Vanessa     60     Karete   F
6     Kate     65    Surfing   F

In [ ]:
df.shape

(7, 4)

In [ ]:
df.tail(2)

name  score    sport sex
5  Vanessa     60   Karete   F
6     Kate     65  Surfing   F

In [ ]:
data.keys()

dict_keys(['name', 'score', 'sport', 'sex'])

In [ ]:
df=pd.DataFrame(data,columns=["name", "sport", "score",
                              "gender","age"],
                index=["one","two","three","four","five","six","seven"])
df.head()

name      sport  score gender  age
one    Bill  Wrestling     90    NaN  NaN
two     Tom   Football     80    NaN  NaN
three   Tim     Skiing     85    NaN  NaN
four   John   Swimming     75    NaN  NaN
five   Alex     Tennis     95    NaN  NaN

In [ ]:
df["sport"]


one      Wrestling
two       Football
three       Skiing
four      Swimming
five        Tennis
six         Karete
seven      Surfing
Name: sport, dtype: object

In [ ]:
type(df['score'])

pandas.core.series.Series

In [ ]:
df.head(2)

name      sport  score gender  age
one  Bill  Wrestling     90    NaN  NaN
two   Tom   Football     80    NaN  NaN

In [ ]:
df[["score", "sport"]]

score      sport
0     90  Wrestling
1     80   Football
2     85     Skiing
3     75   Swimming
4     95     Tennis
5     60     Karete
6     65    Surfing

In [ ]:
df["age"] = 18
df.head()

name      sport  score gender  age
one    Bill  Wrestling     90    NaN   18
two     Tom   Football     80    NaN   18
three   Tim     Skiing     85    NaN   18
four   John   Swimming     75    NaN   18
five   Alex     Tennis     95    NaN   18

In [ ]:
del df['gender']


KeyError: 'gender'

In [ ]:
df.head()

name      sport  score  age
one    Bill  Wrestling     90   18
two     Tom   Football     80   18
three   Tim     Skiing     85   18
four   John   Swimming     75   18
five   Alex     Tennis     95   18

In [ ]:
df2=df
df2.head()

name      sport  score  age
one    Bill  Wrestling     90   18
two     Tom   Football     80   18
three   Tim     Skiing     85   18
four   John   Swimming     75   18
five   Alex     Tennis     95   18

In [ ]:
df2.reset_index()

index     name      sport  score  age
0    one     Bill  Wrestling     90   18
1    two      Tom   Football     80   18
2  three      Tim     Skiing     85   18
3   four     John   Swimming     75   18
4   five     Alex     Tennis     95   18
5    six  Vanessa     Karete     60   18
6  seven     Kate    Surfing     65   18

In [ ]:
df2.reset_index(drop = True)

name      sport  score  age
0     Bill  Wrestling     90   18
1      Tom   Football     80   18
2      Tim     Skiing     85   18
3     John   Swimming     75   18
4     Alex     Tennis     95   18
5  Vanessa     Karete     60   18
6     Kate    Surfing     65   18

In [ ]:
df2.reset_index(drop = True, inplace = True)
df2.head()

name      sport  score  age
0  Bill  Wrestling     90   18
1   Tom   Football     80   18
2   Tim     Skiing     85   18
3  John   Swimming     75   18
4  Alex     Tennis     95   18

In [ ]:
df2.head()

name      sport  score  age
0  Bill  Wrestling     90   18
1   Tom   Football     80   18
2   Tim     Skiing     85   18
3  John   Swimming     75   18
4  Alex     Tennis     95   18

In [ ]:
df2.iloc[1,3]

18

In [ ]:
data = {
    'gender': ['m', 'm', 'm', 'f', 'f'],
    'wt': [60, 70, 80, 60, 70]
}

df = pd.DataFrame(data)
df.head(20)

gender  wt
0      m  60
1      m  70
2      m  80
3      f  60
4      f  70

from matplotlib import pyplot as plt
_df_0['wt'].plot(kind='hist', bins=20, title='wt')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_1.groupby('gender').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_2['wt'].plot(kind='line', figsize=(8, 4), title='wt')
plt.gca().spines[['top', 'right']].set_visible(False)

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_3['gender'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_3, x='wt', y='gender', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

In [ ]:
df.groupby(['gender'])[['wt']].count()

wt
gender    
f        2
m        3

In [ ]:
data = {
    'gender': ['m', 'm', 'm', 'f', 'f'],
    'wt': [60, 70, 80, 60, 70],
    'ht': [160, 170, 180, 160, 170]
}

df = pd.DataFrame(data)
df.head ()

gender  wt   ht
0      m  60  160
1      m  70  170
2      m  80  180
3      f  60  160
4      f  70  170

In [ ]:
df.groupby(['wt'])[['ht','wt']].mean()

ht    wt
wt             
60  160.0  60.0
70  170.0  70.0
80  180.0  80.0

In [ ]:
df.groupby(['gender'])[['ht','wt']].count()

ht  wt
gender        
f        2   2
m        3   3

In [ ]:
data1 = {
    'id': [1, 2],
    'name': ['akash', 'vivek']
}
df1 = pd.DataFrame(data1)
df1

id   name
0   1  akash
1   2  vivek

In [ ]:
data2 = {
    'id': [1, 3],
    'dept': ['analytics', 'tech']
}
df2 = pd.DataFrame(data2)
df2

id       dept
0   1  analytics
1   3       tech

In [ ]:
pd.merge(df1,df2,how = 'outer', on = 'id')

id   name       dept
0   1  akash  analytics
1   2  vivek        NaN
2   3    NaN       tech

In [ ]:
data1 = {
    'id1': [1, 2],
    'name': ['akash', 'vivek']
}
df1 = pd.DataFrame(data1)
df1

id1   name
0    1  akash
1    2  vivek

In [ ]:
data2 = {
    'id2': [1, 3],
    'dept': ['analytics', 'tech']
}
df2 = pd.DataFrame(data2)
df2

id2       dept
0    1  analytics
1    3       tech

In [ ]:
pd.merge(df1,df2,how = 'left', left_on = 'id1', right_on = 'id2')

id1   name  id2       dept
0    1  akash  1.0  analytics
1    2  vivek  NaN        NaN

In [ ]:
pd.merge(df1,df2,how = 'right', left_on = 'id1', right_on = 'id2')

id1   name  id2       dept
0  1.0  akash    1  analytics
1  NaN    NaN    3       tech

In [ ]:
data = {'Category': ['A', 'B', 'A', 'C', 'B', 'A', 'A', 'C'],
        'Value': [10, 20, 15, 25, 30, 12, 18, 22]}
df2 = pd.DataFrame(data)

In [ ]:
df2['Category'].mode()

0    A
Name: Category, dtype: object

In [ ]:
df2['Category'].mode()

0    A
Name: Category, dtype: object

In [ ]:
df2['Value'].mode()[0]

10

In [ ]:
df2['Category'].value_counts()['A']

4

In [ ]:
df2['Value'].value_counts()[10]

1

In [ ]:
df = pd.DataFrame({
    'Category': ['A', 'B', np.nan, np.nan],
    'Age': [25, 30, np.nan, np.nan]
    })

In [ ]:
df.head()

Category   Age
0        A  25.0
1        B  30.0
2      NaN   NaN
3      NaN   NaN

In [ ]:
df.isnull().sum()

Category    2
Age         2
dtype: int64

In [ ]:
df['Age']
# mean/median

0    25.0
1    30.0
2     NaN
3     NaN
Name: Age, dtype: float64

In [ ]:
mean_age = df['Age'].mean()
print(mean_age)

27.5


In [ ]:
df['Age'].fillna(mean_age,inplace=True)

In [ ]:
df.head()

Category   Age
0        A  25.0
1        B  30.0
2      NaN  27.5
3      NaN  27.5

In [ ]:
mod_cat = df['Category'].mode()[0]
print(mod_cat)

A


In [ ]:
df['Category'].fillna(mod_cat, inplace=True)

In [ ]:
df.head()

Category   Age
0        A  25.0
1        B  30.0
2        A  27.5
3        A  27.5

In [ ]:
import numpy as np
import pandas as pd

# The file is stored at the following path:
# 'https://media-doselect.s3.amazonaws.com/generic/NMgEjwkAEGGQZBoNYGr9Ld7w0/rating.csv'
df = pd.read_csv('https://media-doselect.s3.amazonaws.com/generic/NMgEjwkAEGGQZBoNYGr9Ld7w0/rating.csv')

# Provide your answer below
df['Training'] = df['Rating'].apply(lambda x: 'No' if x >4.5 else 'Yes')
print(df.head(20))

print()

       ID Department     Office  Rating Training
0   U2F26    Finance  New Delhi     3.4      Yes
1   U2M61  Marketing  New Delhi     3.9      Yes
2   U1S15      Sales  New Delhi     2.8      Yes
3   U1H87         HR     Mumbai     2.1      Yes
4   U1S51      Sales  New Delhi     4.6       No
5   U1H78         HR  New Delhi     3.8      Yes
6   U3M65  Marketing  New Delhi     5.0       No
7   U3M44  Marketing  Bangalore     2.1      Yes
8   U3S75      Sales  Bangalore     4.3      Yes
9   U2H84         HR  Bangalore     4.3      Yes
10  U2S84      Sales     Mumbai     3.6      Yes
11  U1S50      Sales     Mumbai     4.7       No
12  U2F25    Finance  New Delhi     4.4      Yes
13  U1S75      Sales  Bangalore     3.0      Yes
14  U1H39         HR  New Delhi     4.2      Yes
15  U2F53    Finance  Bangalore     2.7      Yes
16  U1F53    Finance  Bangalore     3.7      Yes
17  U2S99      Sales  New Delhi     3.6      Yes
18  U3F41    Finance  New Delhi     4.9       No
19  U1F28    Finance

In [ ]:
import pandas as pd
df = pd.read_csv('https://cdn.upgrad.com/uploads/production/b3467ba4-4e13-44e9-8087-4d7e94cc7586/forestfires.csv')
by = df.groupby(['month', 'day'])
df_1 = by['rain','wind'].mean()
print(df_1.head(20))

ValueError: Cannot subset columns with a tuple with more than one element. Use a list instead.

In [ ]:
import numpy as np
import pandas as pd

gold = pd.DataFrame({'Country': ['USA', 'France', 'Russia'],
                         'Medals': [15, 13, 9]}
                    )
silver = pd.DataFrame({'Country': ['USA', 'Germany', 'Russia'],
                        'Medals': [29, 20, 16]}
                    )
bronze = pd.DataFrame({'Country': ['France', 'USA', 'UK'],
                        'Medals': [40, 28, 27]}
                    )

gold.set_index('Country', inplace = True)
silver.set_index('Country', inplace = True)
bronze.set_index('Country', inplace = True)

total = pd.concat([gold, silver, bronze]).groupby('Country').sum().\
          sort_values('Medals', ascending=False)
print(total)

         Medals
Country        
USA          72
France       53
UK           27
Russia       25
Germany      20


In [ ]:
data_df=df.pivot(columns='grouping_variable_col', values='value_to_aggregate', index='grouping_variable_row')
data_df.head()

KeyError: 'grouping_variable_row'

In [ ]:
import numpy as np
import pandas as pd
df = pd.read_csv('https://cdn.upgrad.com/uploads/production/b3467ba4-4e13-44e9-8087-4d7e94cc7586/forestfires.csv')
df_1 = df.pivot_table(index = ['month','day'],values = ['rain','wind'],aggfunc = 'mean')
print(df_1.head(20))

               rain      wind
month day                    
apr   fri  0.000000  3.100000
      mon  0.000000  3.100000
      sat  0.000000  4.500000
      sun  0.000000  5.666667
      thu  0.000000  5.800000
      wed  0.000000  2.700000
aug   fri  0.066667  4.766667
      mon  0.000000  2.873333
      sat  0.000000  4.310345
      sun  0.025000  4.417500
      thu  0.000000  3.503846
      tue  0.300000  4.567857
      wed  0.000000  3.520000
dec   fri  0.000000  4.900000
      mon  0.000000  8.500000
      sun  0.000000  8.500000
      thu  0.000000  4.900000
      tue  0.000000  8.500000
      wed  0.000000  8.000000
feb   fri  0.000000  4.820000


# New Section

In [ ]:
#lambda

In [4]:
fibonacci = lambda n: reduce(lambda x, _: x + [x[-1] + x[-2]], range(n-2), [0, 1])

# Get the Fibonacci series up to n terms
result = fibonacci(11)
print(result)

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55]


In [5]:
fib = lambda n: n if n <= 1 else fib(n-1) + fib(n-2)
x = int(input("Enter the range for Fibonacci series: "))

for i in range(x):
    print(fib(i))

Enter the range for Fibonacci series: 4
0
1
1
2


In [ ]:
import random

class Flashcard:
  def __init__(self):
    self.fruits = {
      "banana": "yellow",
      "orange": "orange",
      "apple": "red",

      # Add more fruits and colors as needed
    }

  def play(self):
    fruit, color = random.choice(list(self.fruits.items()))
    guess = input(f"What color is a {fruit}? ")
    if guess.lower() == color.lower():
      print("Correct!")
    else:
      print(f"Wrong. A {fruit} is {color}.")

# Create a flashcard object
flashcard = Flashcard()

# Play the game
while True:
  flashcard.play()
  play_again = input("Play again? (y/n): ")
  if play_again.lower() != "y":
    break

print("Thanks for playing!")

In [ ]:
from collections import Counter

def create_bow(sentences):
  """
  This function takes a list of sentences and returns a list of bag-of-words representations.

  Args:
      sentences: A list of strings representing sentences.

  Returns:
      A list of lists, where each inner list represents the bag-of-words representation
      for the corresponding sentence in the input list.
  """
  # Create a vocabulary of all unique words in the corpus
  vocabulary = set(word for sentence in sentences for word in sentence.lower().split())

  # Function to create a bag-of-words dictionary for a sentence
  def sentence_to_bow(sentence):
    bow_dict = Counter(sentence.lower().split())
    # Fill the dictionary with 0s for missing words in the vocabulary
    for word in vocabulary:
      bow_dict[word] = bow_dict.get(word, 0)
    return list(bow_dict.values())  # Convert dictionary to list

  # Apply the sentence_to_bow function to each sentence
  bow_vectors = [sentence_to_bow(sentence) for sentence in sentences]
  return bow_vectors

# Example usage
sentences = [
  "the quick brown fox jumps over the brown dog",
  "the dog barks loudly",
  "the cat sleeps peacefully"
]

bow_vectors = create_bow(sentences)

print("Sentence 1:", bow_vectors[0])
print("Sentence 2:", bow_vectors[1])
print("Sentence 3:", bow_vectors[2])